use signup;

CREATE TABLE adds (
	id INT AUTO_INCREMENT PRIMARY KEY,  
	userid VARCHAR(100) NOT NULL UNIQUE,
	img BLOB NOT NULL,
	link VARCHAR(255) NOT NULL,
	clothes CHAR(1) NOT NULL, 
	price VARCHAR(200) NOT NULL,
	season VARCHAR(200) NOT NULL
);

