
CREATE DATABASE signup DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

GRANT ALL ON signup.* TO 'web'@'localhost' IDENTIFIED BY 'asdf';

use signup;


CREATE TABLE add (
	id INT AUTO_INCREMENT PRIMARY KEY,  
	userid VARCHAR(100) NOT NULL UNIQUE,
	img VARCHAR(100) NOT NULL,
	link VARCHAR(255) NOT NULL,
	clothes CHAR(1) NOT NULL, 
	price VARCHAR(200) NOT NULL,
	season VARCHAR(200) NOT NULL
	
);

