CREATE DATABASE signup DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

GRANT ALL ON signup.* TO 'web'@'localhost' IDENTIFIED BY 'asdf';

use signup;


CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	userid VARCHAR(100) NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL,
	pwd VARCHAR(255) NOT NULL,
	email VARCHAR(100) UNIQUE,
);

